# Generated by Django 3.1.5 on 2021-06-10 19:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210609_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=150, verbose_name='ФИО')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='ИД пользователя')),
                ('inn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='company.company', verbose_name='ИНН компании')),
            ],
        ),
    ]
