# Generated by Django 3.1.5 on 2021-06-11 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Персона', 'verbose_name_plural': 'Персоны'},
        ),
    ]
