# Generated by Django 3.1.5 on 2021-06-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20210611_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='inn',
            new_name='company',
        ),
    ]
