# Generated by Django 3.1.5 on 2021-06-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20210611_1316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='inn',
            new_name='company',
        ),
    ]
