# Generated by Django 3.1.5 on 2021-06-14 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20210612_1319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Лицензия', 'verbose_name_plural': 'Лицензии'},
        ),
    ]
