# Generated by Django 3.1.5 on 2021-06-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20210614_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
    ]
